name: Dsiplay Secrets

on:
  workflow_dispatch:
  
jobs:
  Display:
    runs-on: ubuntu-latest
    steps:
    
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: Display Secrets
        run: |
          echo $AZURE_CREDENTIALS
        
          
