name: Dsiplay Secrets

on:
  workflow_dispatch:
  
jobs:
  Display:
    runs-on: ubuntu-latest
    steps:
    
      # Checks out the repository this file is in
      - uses: actions/checkout@v3

      - name: Set up secret file
        env:
          DEBUG_PASSWORD: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo $DEBUG_PASSWORD
  
        
          
