name: Multi Environment

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: print single statement
      run: echo Hello, Build!
       
  deployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: print single statement
      run: echo Hello, Dev!
      
  deployProd:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deployDev
    steps:
    - name: print single statement
      run: echo Hello, Prod!
